name: sisonke
description: Sisonke - South Africans Helping South Africans
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/brand/
